const hoursAgo = (hours) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export function createDemoData() {
  return {
    version: 1,
    projects: [
      {
        id: "project-workspace",
        name: "个人工作台",
        status: "进行中",
        path: "D:\\Projects\\personal-workspace",
        github: "https://github.com",
        url: "https://example.com",
        stage: "产品原型",
        next: "完成首页信息架构并邀请一位朋友试用",
        description: "把分散的项目、资料、决策和待办放进一个轻量的个人工作空间。",
        createdAt: hoursAgo(72),
      },
      {
        id: "project-reading",
        name: "阅读清单整理",
        status: "计划中",
        path: "D:\\Projects\\reading-list",
        github: "https://github.com",
        url: "",
        stage: "需求梳理",
        next: "从收件箱挑出 10 条真正想读的文章",
        description: "建立一个不需要复杂分类、但容易回看的阅读资料库。",
        createdAt: hoursAgo(96),
      },
      {
        id: "project-weekly-review",
        name: "每周回顾流程",
        status: "进行中",
        path: "D:\\Projects\\weekly-review",
        github: "https://github.com",
        url: "",
        stage: "流程试跑",
        next: "周五花 15 分钟记录本周完成和下周重点",
        description: "用固定的简短问题整理一周的进展、阻塞和下一步。",
        createdAt: hoursAgo(120),
      },
    ],
    tasks: [
      { id: "task-home", title: "梳理首页要显示的 6 类信息", projectId: "project-workspace", priority: "高", status: "todo", due: "今天", createdAt: hoursAgo(3) },
      { id: "task-search", title: "列出全局搜索需要覆盖的字段", projectId: "project-workspace", priority: "中", status: "todo", due: "明天", createdAt: hoursAgo(7) },
      { id: "task-review", title: "检查手机窄屏下的导航布局", projectId: "project-workspace", priority: "中", status: "todo", due: "本周", createdAt: hoursAgo(22) },
      { id: "task-articles", title: "整理 10 篇待读文章", projectId: "project-reading", priority: "高", status: "todo", due: "本周", createdAt: hoursAgo(30) },
      { id: "task-review-template", title: "写下每周回顾的三个固定问题", projectId: "project-weekly-review", priority: "低", status: "todo", due: "周五", createdAt: hoursAgo(39) },
      { id: "task-demo", title: "为项目准备演示资料", projectId: "project-workspace", priority: "低", status: "done", due: "", createdAt: hoursAgo(56) },
    ],
    knowledge: [
      { id: "knowledge-first-principles", type: "笔记", title: "工作台首页应该回答什么", content: "打开首页时，先让我知道手头有哪些项目、哪件事最该推进，以及最近做过什么。不要用一堆图表占据注意力。", summary: "首页优先展示现状、下一步和最近变化。", tags: ["产品", "首页"], projectId: "project-workspace", createdAt: hoursAgo(4) },
      { id: "knowledge-search", type: "文本", title: "搜索的第一版范围", content: "在一个输入框里搜索项目名、资料标题和正文、决策问题、任务标题。结果需要标出所属类别，并且能直接打开。", summary: "统一入口搜索四种主要记录。", tags: ["搜索", "交互"], projectId: "project-workspace", createdAt: hoursAgo(14) },
      { id: "knowledge-platform-notes", type: "文本", title: "Supabase 与 GitHub Pages 参考备注", content: "这是用于演示全局搜索的 Mock 资料。V1 只使用 localStorage，没有连接 Supabase，也不会自动发布到 GitHub Pages。", summary: "可搜索的本地示例；云端同步和自动发布留待后续评估。", tags: ["Supabase", "GitHub Pages", "Mock"], projectId: "project-workspace", createdAt: hoursAgo(9) },
      { id: "knowledge-reading", type: "链接", title: "渐进式整理资料的想法", content: "https://example.com/notes", summary: "先保存，再决定是否分类；标签只作辅助。", tags: ["阅读", "知识管理"], projectId: "project-reading", createdAt: hoursAgo(28) },
      { id: "knowledge-weekly", type: "笔记", title: "每周回顾草稿", content: "1. 这周什么事情向前推进了？\n2. 哪个问题反复占用注意力？\n3. 下周最重要的一步是什么？", summary: "三问式回顾，控制在 15 分钟内。", tags: ["复盘", "习惯"], projectId: "project-weekly-review", createdAt: hoursAgo(46) },
    ],
    decisions: [
      {
        id: "decision-local-first",
        question: "工作台第一版应该用什么方式保存数据？",
        options: ["本地 localStorage", "先接远端数据库"],
        goal: "先验证页面结构和个人使用流程。",
        time: "本地方案更快，约半天；接数据库需要额外配置。",
        cost: "本地方案几乎没有运行成本。",
        risk: "换设备时需要手动迁移浏览器数据。",
        recommendation: "先用 localStorage 完成闭环，再根据真实使用决定同步方案。",
        final: "本地 localStorage",
        reason: "当前重点是验证工作流；先把可操作的产品做出来，再评估同步方式。",
        projectId: "project-workspace",
        createdAt: hoursAgo(18),
      },
      {
        id: "decision-light-tags",
        question: "资料要不要强制要求选分类？",
        options: ["强制选择分类", "可选标签和项目关联"],
        goal: "让资料可以快速收进来，也能按项目找回。",
        time: "可选字段减少每次录入步骤。",
        cost: "不增加额外服务或维护。",
        risk: "资料量变大后可能需要更好的筛选。",
        recommendation: "先让标签和项目关联可选，避免录入门槛。",
        final: "可选标签和项目关联",
        reason: "先保证捕捉速度，之后再观察是否需要更严格的分类。",
        projectId: "project-reading",
        createdAt: hoursAgo(42),
      },
    ],
    activities: [
      { id: "activity-task", type: "task-done", title: "完成任务「为项目准备演示资料」", projectId: "project-workspace", createdAt: hoursAgo(2) },
      { id: "activity-knowledge", type: "knowledge-added", title: "新增资料「工作台首页应该回答什么」", projectId: "project-workspace", createdAt: hoursAgo(4) },
      { id: "activity-decision", type: "decision-saved", title: "保存决策「工作台第一版应该用什么方式保存数据？」", projectId: "project-workspace", createdAt: hoursAgo(18) },
      { id: "activity-project", type: "project-created", title: "开始了项目「个人工作台」", projectId: "project-workspace", createdAt: hoursAgo(72) },
      { id: "activity-task-new", type: "task-added", title: "创建任务「整理 10 篇待读文章」", projectId: "project-reading", createdAt: hoursAgo(30) },
      { id: "activity-knowledge-weekly", type: "knowledge-added", title: "新增资料「每周回顾草稿」", projectId: "project-weekly-review", createdAt: hoursAgo(46) },
    ],
  };
}
